#ifndef ERROR_CODES_H
#define ERROR_CODES_H


typedef enum
{
  ERROR_CODE_NO_ERROR,
  ERROR_CODE_INTERNAL_ERROR,
  ERROR_CODE_INVALID_INPUT,
  ERROR_CODE_INVALID_OUTPUT,
  ERROR_CODE_INVALID_RETURN_BUFFER,
  ERROR_CODE_INVALID_INPUT_PARAMETERS,
  ERROR_CODE_INVALID_OUTPUT_PARAMETERS,
  ERROR_CODE_DISPLAY_SENSOR_NOT_CONFIGURED,
  ERROR_CODE_DISPLAY_INVALID_MEASUREMENT_TYPE,
  ERROR_CODE_INVALID_INPUT_TYPE,
  ERROR_CODE_DISPLAY_CURRENT_I2C_ADDR_OUT_OF_RANGE,
  ERROR_CODE_INVALID_OUTPUT_PAYLOAD_LEN,
  ERROR_CODE_SENSORS_NO_SENSORS_CONFIGURED,
  ERROR_CODE_SENSORS_SENSOR_NOT_FOUND,
  ERROR_CODE_SENSORS_INVALID_MEASUREMENT_TYPE,
  ERROR_CODE_SENSORS_MEASUREMENT_TYPE_MISSING_FUNCTION,
  ERROR_CODE_SENSORS_INVALID_VALUE_FROM_SENSOR,
  ERROR_CODE_SENSORS_ABNORMAL_VALUE,
  ERROR_CODE_OUTPUT_ROUTER_DATA_CONTAINS_ERRORS,
  ERROR_CODE_RTC_RTC_NOT_FOUND,
  ERROR_CODE_RTC_INIT_FAILED
} error_manager_error_code_te;

#endif